window.CLI_COURSE = window.CLI_COURSE || { modules: [], exam: null, cheatsheet: null };
window.CLI_COURSE.exam = {
  id: "exam", title: "Фінальний іспит", passPercent: 80,
  quiz: [
    { title: "Запуск", question: "Ти хочеш, щоб агент допоміг з проєктом `demo`. Найкращий старт?", options: ["`cd ~/Projects/demo`, `git status`, потім `grok`", "`grok` з домашньої папки", "`grok --yolo` з кореня диска"], correct: 0, feedback: "Папка проєкту обмежує доступ, `git status` фіксує стан до агента." },
    { title: "Довідка", question: "Прапорця зі статті немає у твоєму `grok --help`. Висновок?", options: ["Стаття точно права — треба перевстановити Grok", "Прапорці залежать від версії: довіряй `grok --help` і docs.x.ai", "Прапорець працює, просто прихований"], correct: 1, feedback: "Grok CLI швидко змінюється; джерело правди — твоя версія і офіційна документація." },
    { title: "Ввід", question: "Ти ввів `/context` у zsh і отримав помилку. Чому?", options: ["Контекст переповнений", "Потрібен `sudo`", "Slash-команди працюють лише всередині TUI `grok`"], correct: 2, feedback: "У zsh `/context` — це шлях до файлу, а не команда." },
    { title: "Сесії", question: "Нова, не пов'язана задача посеред довгої сесії. Що зробити?", options: ["`/new` і `/rename` з назвою задачі", "`/compact-mode`", "Продовжити в тій самій сесії"], correct: 0, feedback: "Нова сесія — чистий контекст; стара лишається збереженою." },
    { title: "Продовження", question: "Як з shell продовжити найсвіжішу сесію для поточної папки?", options: ["`grok -p`", "`grok -c`", "`grok -w`"], correct: 1, feedback: "`-c` / `--continue`; `-p` — headless, `-w` — worktree." },
    { title: "Share", question: "Що перевірити перед `/share`?", options: ["Тему інтерфейсу", "Модель", "Чи немає в транскрипті токенів, паролів і внутрішніх адрес"], correct: 2, feedback: "Посилання відкриває весь транскрипт." },
    { title: "Контекст", question: "`/context` показує 85 %, етап роботи завершено. Що доречно?", options: ["`/compact` з підказкою, що зберегти", "`/compact-mode`", "`/theme`"], correct: 0, feedback: "`/compact [context]` стискає історію; `/compact-mode` — лише вигляд." },
    { title: "Відкат", question: "Що `/rewind` робить з файлами на диску?", options: ["Нічого — відкочує лише розмову", "Відновлює їх до стану в обраній точці; незакомічені зміни після неї втрачаються", "Видаляє всі файли проєкту"], correct: 1, feedback: "Rewind відновлює файли й обрізає розмову. Перед ним — `git diff` і `git commit` або `git stash`." },
    { title: "Plan", question: "Що можуть редагувати edit tools агента в plan mode до схвалення плану?", options: ["Будь-які файли з питанням", "Лише файли тестів", "Лише файл плану сесії"], correct: 2, feedback: "Edit tools до схвалення змінюють лише план у будь-якому режимі; bash не заблоковано — він іде за режимом дозволів." },
    { title: "Модель", question: "`/model grok-3` зі старого туторіалу не працює. Що робити?", options: ["Перевірити актуальний список через `grok models`", "Перевстановити macOS", "Ввести `/model` кілька разів"], correct: 0, feedback: "Назви моделей змінюються; список дає `grok models`." },
    { title: "Режими", question: "Хочеш, щоб безпечні дії проходили без запитів, а небезпечні — з запитом. Який режим?", options: ["Always-approve", "Auto (`/auto`)", "Plan"], correct: 1, feedback: "Auto — класифікатор схвалює безпечні tools; небезпечні можуть питати. Ризик середній." },
    { title: "Always-approve", question: "Що з цього — найризикованіше?", options: ["`/auto`", "`/plan`", "`grok --always-approve` у продакшн-репозиторії без коміту"], correct: 2, feedback: "Без запитів і без точки відкату — дії агента можуть бути незворотні." },
    { title: "Правила", question: "Allow `*` і deny `rm -rf *` для bash. Агент хоче `rm -rf build`. Що буде?", options: ["Заборонено: deny перемагає allow", "Виконається", "Залежить від моделі"], correct: 0, feedback: "У Grok deny завжди перемагає allow, навіть в always-approve." },
    { title: "Розширення", question: "Як з shell одним списком побачити правила, skills, plugins, hooks і MCP, які підхопить Grok?", options: ["`grok models`", "`grok inspect`", "`/hooks`"], correct: 1, feedback: "`grok inspect` — аудит усього, що знайдено; `/hooks` — лише вкладка в TUI." },
    { title: "Пам'ять", question: "Треба прибрати один застарілий спогад агента. Найбезпечніше?", options: ["`grok memory clear --all`", "Перевстановити Grok", "Видалити або відредагувати запис у `/memory`"], correct: 2, feedback: "Точкова зміна замість безповоротного очищення всього." },
    { title: "Skills", question: "Два skills з іменем `commit`. Як викликати саме локальний?", options: ["`/local:commit`", "`/commit local`", "`/skills commit`"], correct: 0, feedback: "Кваліфікована форма `/<scope>:<name>`." },
    { title: "Workflow", question: "Агент закінчив задачу. Який крок обов'язковий перед комітом?", options: ["`git push --force`", "`git diff` — переглянути всі зміни", "`/always-approve`"], correct: 1, feedback: "Спершу бачиш, потім комітиш." },
    { title: "Автоматизація", question: "Хочеш дати агенту свободу для експерименту, не ризикуючи основною гілкою. Що обрати?", options: ["`grok --yolo` у `main`", "`/compact`", "`grok -w experiment` — окремий worktree"], correct: 2, feedback: "Worktree — окрема робоча копія (detached на поточному коміті, з копією незакомічених змін), тож правки файлів не змішуються з основною папкою. Shell агента worktree не ізолює — для цього `--sandbox`." }
  ]
};
